# Generated by Django 5.2.5 on 2025-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='title',
            field=models.CharField(default='sin titulo', max_length=255),
            preserve_default=False,
        ),
    ]
