# Generated by Django 5.2.5 on 2025-08-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_objective_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
