# Generated by Django 5.2.5 on 2025-08-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_objective_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='checkpoints',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='focus',
            field=models.CharField(blank=True, choices=[('Depth', 'Depth'), ('Breadth', 'Breadth'), ('Speed', 'Speed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='formats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='session_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
